const DATA = [
  {
    id: 1,
    qustionText: 'qustionTe xt1qustion Text1qustionText1q usti onText1qustionTe xt1qustionText1qus tionText1qustionText1qustionText 1qustionTe xt1qustio nText1qustionTe xt1qustionText1',
    questionImg: 'test1',
    questionAudio: 'name1',
    arrayAnswers: ['test', 'otvet2', 'otver3', 'otet4'],
  },
  {
    id: 2,
    qustionText: 'qustionText2qustionText2qustionText2qustionText 2qustionText 2qustionText 2qustionText 2qustionText 2qustionText 2qustionText 2qustionText 2qustionText 2qustionText 2qustionText 2qustionText 2qustionText 2',
    questionImg: 'test2',
    questionAudio: 'name2',
    arrayAnswers: ['test', 'otvet2', 'otver3', 'otet4', 'otet4', 'otet4'],
  },
  {
    id: 3,
    qustionText: 'qustionText3qustion Text3qustion Text3qustion Text3qustion Text3qustion Text3qustion Text3',
    questionImg: 'test3',
    questionAudio: 'name3',
    arrayAnswers: ['test', 'otvet2', 'otver3', 'otet4'],
  },
  {
    id: 4,
    qustionText: 'qustionText4',
    questionImg: 'test4',
    questionAudio: 'name3',
    arrayAnswers: ['test', 'otvet2', 'otver3', 'otet4'],
  },
  {
    id: 5,
    qustionText: 'qustionText5',
    questionImg: 'test5',
    questionAudio: 'name5',
    arrayAnswers: ['test', 'otvet2', 'otver3', 'otet4', 'otet4'],
  },
  {
    id: 6,
    qustionText: 'qustionText6',
    questionImg: 'test6',
    questionAudio: 'name6',
    arrayAnswers: ['test', 'otvet2', 'otver3', 'otet4', 'otet4'],
  },
  {
    id: 7,
    qustionText: 'qustionText7',
    questionImg: 'test7',
    questionAudio: 'name7',
    arrayAnswers: ['test', 'otvet2', 'otver3', 'otet4', 'otet4'],
  },
  {
    id: 8,
    qustionText: 'qustionText8',
    questionImg: 'test7',
    questionAudio: 'name7',
    arrayAnswers: ['test', 'otvet2', 'otver3', 'otet4', 'otet4'],
  },
  {
    id: 9,
    qustionText: 'qustionText9',
    questionImg: 'test7',
    questionAudio: 'name7',
    arrayAnswers: ['test', 'otvet2', 'otver3', 'otet4', 'otet4'],
  },
  {
    id: 10,
    qustionText: 'qustionText10',
    questionImg: 'test7',
    questionAudio: 'name7',
    arrayAnswers: ['test', 'otvet2', 'otver3', 'otet4', 'otet4'],
  },
  {
    id: 11,
    qustionText: 'qustionText11',
    questionImg: 'test7',
    questionAudio: 'name7',
    arrayAnswers: ['test', 'otvet2', 'otver3', 'otet4', 'otet4'],
  },
  {
    id: 12,
    qustionText: 'qustionText12',
    questionImg: 'test7',
    questionAudio: 'name7',
    arrayAnswers: ['test', 'otvet2', 'otver3', 'otet4', 'otet4'],
  },
  {
    id: 13,
    qustionText: 'qustionText13',
    questionImg: 'test7',
    questionAudio: 'name7',
    arrayAnswers: ['test', 'otvet2', 'otver3', 'otet4', 'otet4'],
  },
  {
    id: 14,
    qustionText: 'qustionText14',
    questionImg: 'test7',
    questionAudio: 'name7',
    arrayAnswers: ['test', 'otvet2', 'otver3', 'otet4', 'otet4'],
  },
  {
    id: 15,
    qustionText: 'qustionText15',
    questionImg: 'test7',
    questionAudio: 'name7',
    arrayAnswers: ['test', 'otvet2', 'otver3', 'otet4', 'otet4'],
  },
];


export {DATA}
